(display "hello world")
(newline)
(display "hello scheme")
(newline)
(define (fib n)
  (if (< n 2) n (+ (fib (- n 1))
                   (fib (- n 2)))))
;(display (fib 9))
;(print "What is your name?")
;(print "Hello, "(read)"!")